config/routes.php
<?php

/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login',]);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->connect('/delete-post', ['controller' => 'Posts', 'action' => 'delete',]);
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/PostsTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Posts Model
 *
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\ParentPostsTable&\Cake\ORM\Association\BelongsTo $ParentPosts
 * @property \App\Model\Table\PostCommentsTable&\Cake\ORM\Association\HasMany $PostComments
 * @property \App\Model\Table\PostLikesTable&\Cake\ORM\Association\HasMany $PostLikes
 *
 * @method \App\Model\Entity\Post get($primaryKey, $options = [])
 * @method \App\Model\Entity\Post newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Post[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Post|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Post saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Post patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Post[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Post findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PostsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->setTable('posts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
        $this->addBehavior('Timestamp');
        $this->belongsTo(
            'Users',
            [
                'foreignKey' => 'user_id',
                'joinType' => 'INNER'
            ]
        );
        $this->belongsTo(
            'hasRelation',
            [
                'className' => 'Followers',
                'foreignKey' => false,
                'conditions' => [
                    'OR' => [
                        'hasRelation.user_id_from = Posts.user_id',
                        'hasRelation.user_id_to = Posts.user_id',
                    ],
                    'hasRelation.is_deleted' => 0
                ]
            ]
        );
        $this->hasMany(
            'PostComments',
            [
                'foreignKey' => 'post_id'
            ]
        );
        $this->hasMany(
            'PostLikes',
            [
                'foreignKey' => 'post_id',
                'conditions' => [
                    'is_deleted' => 0
                ]
            ]
        );
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('description')
            ->requirePresence('description', 'create')
            ->notEmptyString('description')
            ->add(
                'description',
                [
                    'maxLength' => [
                        'rule' => ['maxLength', 140],
                        'message' => '140 characters is a maximum length'
                    ],
                    'notBlank' => [
                        'rule' => 'notBlank',
                        'message' => 'Description can not be empty',
                        'last' => true
                    ],
                ]
            );

        /**
         * Image
         */
        $validator
            ->allowEmptyFile('image')
            ->add(
                'image',
                [
                    'extension' => [
                        'rule' => function ($value, $context) {
                            $return = true;
                            $fileData = pathinfo($value['name']);
                            $ext = $fileData['extension'];
                            $allowExtension = ['gif', 'GIF', 'jpeg', 'JPEG', 'png', 'PNG', 'jpg', 'JPG'];
                            if (in_array($ext, $allowExtension)) {
                                $return = true;
                            } else {
                                $return = false;
                            }
                            /** Rutrun boolean */
                            return $return;
                        },
                        'message' => 'Invalid file type'
                    ],
                ]
            );

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        /** Rutrun added rules */
        return $rules;
    }
}

src/Template/Element/comment.ctp
                                            <div class="card-body">
                                                <small><span class="text-dark">Enter comment here:</span></small>
                                                <a href="javascript:void(0)" class="link m-r-10 float-right"><i class="ti-close fa-sm text-danger close-comment"></i></a>
                                                <div class="chat-box" id="chat" style="position: relative; max-height:280px; overflow: auto;">
                                                    <ul class="chat-list">
                                                        <li ng-repeat="comment in data">
                                                            <div class="chat-img"><img ng-src="/img/blog/profile/{{comment.user.image}}" alt="user" width: 50px; height: 50px;></div>
                                                            <div class="chat-content">
                                                                <h5><small>{{ comment.user.fullname }}</small></h5>
                                                                <div class="box bg-light-info"><small>{{ comment.description }}</small></div>
                                                            </div>
                                                            <div class="chat-time"><small>{{ comment.created | date:'M/d/yy, h:mm a' }}</small></div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>

src/Template/Element/navbar.ctp
<?php
$user = $this->Session->read('Auth.User');
?>
<?= $this->Html->script('/js/sidebarmenu.js') ?>
<div id="nav_bar">
    <header class="topbar" style="background-color: #bdc1c9">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <div class="navbar-collapse">
                <a class="navbar-brand" href="/posts">
                    <img src="/img/logo_auth1.png" alt="homepage" class="light-logo" width="60" />
                </a>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <?php
                        echo $this->Form->create(
                            'Users',
                            array(
                                'url' => array('controller' => 'Followers', 'action' => 'index'),
                                'type' => 'delete',
                                'class' => 'app-search d-none d-md-block d-lg-block'
                            )
                        );
                        $userSearch = '';
                        if (isset($searchUser)) {
                            $userSearch = $searchUser;
                        } ?>
                        <input type="text" class="form-control" placeholder="Search & enter" name="search_user" value="<?= $userSearch ?>">
                        <?php
                        echo $this->Form->end();
                        ?>

                    </li>
                </ul>
                <ul class="navbar-nav my-lg-0">
                    <li class="nav-item dropdown u-pro">
                        <a class="nav-link dropdown-toggle waves-effect waves-dark profile-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="/img/blog/profile/<?= h($user['image']) ?>" alt="user"> <span class="text-dark"> <?= h($user['fullname']) ?> &nbsp;<i class="fa fa-angle-down"></i></span> </a>
                        <div class="dropdown-menu dropdown-menu-right animated flipInY">
                            <a href="/users/profile/<?= h($user['id']) ?>" class="dropdown-item"><i class="ti-user"></i> My Profile</a>
                            <a href="/users/update-user" class="dropdown-item"><i class="ti-user"></i> Update Account</a>
                            <a href="/users/update-profile-pic" class="dropdown-item"><i class="ti-user"></i> Change Profile Pic</a>
                            <a href="/users/change-password" class="dropdown-item"><i class="ti-user"></i> Change password</a>
                            <a href="/users/logout" class="dropdown-item"><i class="fa fa-power-off"></i> Logout</a>

                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/posts">MicroBlogChaste</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item" id="home">
                <a class="nav-link" href="/posts">Home</a>
            </li>
            <li class="nav-item" id="follow">
                <a class="nav-link" href="/followers">Follow Someone</a>
            </li>
        </ul>
    </div>
</nav>

src/Template/Element/post_block.ctp
<?php $user = $this->Session->read('Auth.User'); ?>
<div class="col-lg-8 col-xlg-9 col-md-7 shadow-sm p-3 mb-5 bg-white rounded">
    <div class="card">
        <ul class="nav nav-tabs profile-tab" role="tablist">
            <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home" role="tab">NewsFeed</a> </li>
            <li class="mr-auto"></li>
            <li class="nav-item">
                <?php
                if (isset($postPage) || isset($profilePage)) {
                    echo $this->Form->create(
                        'Posts',
                        array(
                            'url' => array('controller' => 'Posts', 'action' => 'index'),
                            'type' => 'delete',
                            'class' => 'app-search d-none d-md-block d-lg-block search_form'
                        )
                    );
                    ?>
                    <input type="text" class="form-control border-dark" placeholder="Search description & enter" name="search_post_description" value="<?= $search ?>">
                <?php
                }
                echo $this->Form->end();
                ?>

            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="home" role="tabpanel">
                <div class="card-body">
                    <div class="profiletimeline">
                        <?php foreach ($postsDetail as $post) { ?>
                            <div class="sl-item">
                                <div class="sl-left"> <img src="/img/blog/profile/<?= h($post->user->image) ?>" alt="user" class="img-circle"/> </div>
                                <?php if ($user['id'] == $post->user->id) { ?>
                                    <a href="javascript:post().delete(<?= $post->id ?>)" class="link m-r-10 float-right"><i class="ti-close fa-sm text-danger"></i></a>
                                    <a href="/posts/updatePost/<?= h($post->id); ?>" class="link m-r-10 float-right"><i class="ti-pencil fa-sm"></i></a>
                                <?php } ?>
                                <div class="sl-right">
                                    <div> <a href="/users/profile/<?= h($post->user->id) ?>" class="link text dark"><?= h($post->user->fullname) ?></a>
                                        <div class="m-t-20 row">
                                            <?php if ($post->image != '') { ?>
                                                <div class="col-md-3 col-xs-12"><img src="/img/blog/post/<?= h($post->image) ?>" alt="user" class="img-responsive radius" /></div>
                                            <?php } ?>
                                            <div class="col-md-9 col-xs-12">
                                                <p> <small><?= h($post->description) ?></small></p>
                                            </div>
                                        </div>
                                        <?php
                                            $toBeShare = $post->id;
                                            if ($post->parent_post_id != null) {
                                                $toBeShare = $post->parent_post_id;
                                                ?>
                                            <?= $this->requestAction('/posts/getParentPost/' . $post->parent_post_id . '/' . $post->id . '/' . $post->user->id, ['return']); ?>
                                        <?php } ?>
                                        <div class="like-comm m-t-20">
                                            <a href="javascript:post().insertLike(<?= $post->id; ?>)" class="link m-r-10 text-primary"><i class="icon-like fa-sm"></i> <small> <span class="like_<?= $post->id; ?>"><?= count($post->post_likes) ?></span> Like</small></a>
                                            <a href="javascript:void(0)" ng-click="show_comment(<?= h($post->id); ?>, 0)" class="link m-r-10 text-primary"><i class="ti-eye fa-sm"></i> <small>comment</small></a>
                                            <a href="#" data-toggle="modal" data-target="#exampleModalCenter" onclick="setParentId(<?= $toBeShare; ?>, <?= h($this->requestAction('/posts/showToBeShare/' . $toBeShare, ['return'])); ?>);" class="link m-r-10 text-primary"><i class="icon-action-redo fa-sm"></i> <small>Share</small></a>
                                            <span class="sl-date float-lg-right"><small><?= h($post->created); ?></small></span>
                                        </div>
                                        <div class="card border border-light shadow-sm rounded-top rounded-bottom comment_section" id="comment_section_<?= h($post->id); ?>">
                                            <?= $this->element('comment'); ?>
                                            <div class="card-body border-top">
                                                <nav aria-label="..." class="load-more-button">
                                                    <ul class="pagination">
                                                        <li class="page-item">
                                                            <a class="page-link" href="#comment_section_<?= h($post->id); ?>" ng-click="show_comment(<?= h($post->id); ?>, 3)">Load More</a>
                                                        </li>
                                                    </ul>
                                                </nav>
                                                <div class="row">
                                                    <div class="col-11">
                                                        <textarea placeholder="Comment something here" class="form-control" id="comment_description<?= h($post->id); ?>"></textarea>
                                                        <label class="error-message-comment">Maximum characters are 140 only</label>
                                                    </div>
                                                    <div class="col-1 text-right">
                                                        <button type="button" onclick="comment().add(<?= h($post->id); ?>)" ng-click="show_comment(<?= h($post->id); ?>,1)" class="btn btn-info"><i class="fas fa-paper-plane"></i> </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                        <?php } ?>
                        <center>
                            <?php if ($search != '') { ?>
                                <p>
                                    Searched result for the name and post description with '<?= h($search); ?>'
                                </p>
                            <?php } ?>
                            <div class="paginator">
                                <ul class="pagination_post">
                                    <?= $this->Paginator->first('<< ' . __('First ')) ?>
                                    <?php if ($this->Paginator->hasPrev()) {
                                        echo $this->Paginator->prev('< ' . __('Previous '));
                                    } ?>
                                    <?= $this->Paginator->numbers() ?>
                                    <?php
                                    if ($this->Paginator->hasNext()) {
                                        echo $this->Paginator->next(__('Next') . ' >');
                                    }
                                    ?>
                                    <?= $this->Paginator->last(__('Last') . ' >>') ?>
                                </ul>
                                <p><small><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></small></p>
                            </div>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
<?= $this->Html->script('/js/controller/comment_script.js'); ?>
<?= $this->Html->script('/js/controller/post_script.js'); ?>

src/Template/Element/post_creation.ctp
<?php $user = $this->Session->read('Auth.User'); ?>
<div class="row">
    <div class="col-lg-4 col-xlg-3 col-md-5">
        <?php if (isset($profilePage)) { ?>
            <?= $this->element('profile_block_info'); ?>
        <?php } ?>
        <?php if (isset($profilePage) && $profilePage['id'] == $user['id'] || isset($postPage) || isset($updatePost)) { ?>
            <?php
                $imgSrc = false;
                if (isset($updatePost)) {
                    $imgSrc = "/img/blog/post/" . h(h($posts['image']));
                    if ($posts['image'] == '') {
                        $imgSrc = '';
                    }
                }
                ?>
            <div class="card sticky-top shadow-sm bg-white rounded">
                <div class="card-body">
                    <?= $this->Form->create(
                            $posts,
                            [
                                'type' => 'post',
                                'enctype' => 'multipart/form-data',
                                'class' => 'floating-labels m-t-40',
                                'onsubmit' => 'disableField()'
                            ]
                        ) ?>
                    <div class="form-group">
                        <?= $this->Form->control(
                                'description',
                                [
                                    'class' => 'form-control has-success m-b-40',
                                    'type' => 'textarea',
                                    'rows' => '5',
                                    'label' => 'What are you thinking?'
                                ]
                            ) ?>
                        <?php if ($imgSrc != '' && isset($updatePost)) { ?>
                            <a class="float-right" href="/posts/removeImage/<?= $posts->id ?>"><button type="button" class="btn btn-danger"> Remove Image</button> </a>
                        <?php } ?>
                        <?= $this->Form->control(
                                'image',
                                [
                                    'type' => 'file',
                                    'id' => 'input-file-now',
                                    'class' => 'dropify',
                                    'data-max-file-size' => '2M',
                                    'label' => false,
                                    'data-default-file' => $imgSrc
                                ]
                            ) ?>
                        <br>
                        <div class="container text-center">
                            <div class="row align-items-start">
                                <div class="col">
                                    <div class="row button-group">
                                        <div class="col-lg-12">
                                            <?= $this->Form->control('Submit Post', [
                                                    'type' => 'submit',
                                                    'class' => 'btn btn-rounded btn-block btn-outline-success submit',
                                                    'label' => false,
                                                    'id' => 'submit_post'
                                                ]) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?= $this->Form->end() ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <?= $this->Html->script('http://jeremyfagis.github.io/dropify/dist/js/dropify.min.js') ?>
    <?= $this->Html->css('http://jeremyfagis.github.io/dropify/dist/css/dropify.min.css') ?>
    <script>
        $(document).ready(function() {
            // Basic
            var s;
            $('.dropify').dropify({
                allowedFileExtensions: ["gif", "GIF", "jpeg", "JPEG", "png", "PNG", "jpg", "JPG"]
            });

            // Used events
            var drEvent = $('#input-file-events').dropify();

            drEvent.on('dropify.beforeClear', function(event, element) {
                return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
            });
            s

            drEvent.on('dropify.afterClear', function(event, element) {
                alert('File deleted');
            });

            drEvent.on('dropify.errors', function(event, element) {
                console.log('Has Errors');
            });

            var drDestroy = $('#input-file-to-destroy').dropify();
            drDestroy = drDestroy.data('dropify')
            $('#toggleDropify').on('click', function(e) {
                e.preventDefault();
                if (drDestroy.isDropified()) {
                    drDestroy.destroy();
                } else {
                    drDestroy.init();
                }
            })
        });
    </script>

src/Template/Element/profile_block_info.ctp
<?php $user = $this->Session->read('Auth.User'); ?>
<div class="card shadow-sm p-3 bg-white rounded">
    <div class="card-body">
        <?= $this->requestAction('/users/checkIfFollowed/' . $profilePage['id'], ['return']); ?>
        <center class="m-t-30"> <img src="/img/blog/profile/<?= $profilePage['image'] ?>" class="img-circle" width="150" />
            <h4 class="card-title m-t-10"><?= h($profilePage['fullname']); ?></h4>
            <div class="row text-center justify-content-md-center">
                <div class="col-4">
                    <a class="link" href="/users/following/<?= $profilePage['id'] ?>"><i class=" icon-user-following text-primary"> Following </i>
                        <font class="font-medium text-primary"><?= $totalFollower; ?></font>
                    </a>
                </div>
                <div class="col-4">
                    <a class="link" href="/users/follower/<?= $profilePage['id'] ?>"><i class="icon-user-follow text-primary"> Follower </i>
                        <font class="font-medium text-primary"><?= $totalFollowing; ?></font>
                    </a>
                </div>
            </div>
            <br>
            <small class="text-muted"><?= h($profilePage['bio']); ?></small>
        </center>
    </div>
    <div>
        <hr>
    </div>
    <div class="card-body">
        <small class="text-muted">Email address </small>
        <h6><?= h($profilePage['email']); ?></h6>
        <small class="text-muted p-t-30 db">Age</small>
        <h6><?= h($profilePage['age']); ?></h6>
        <small class="text-muted p-t-30 db">Address</small>
        <h6><?= h($profilePage['address']); ?></h6>
    </div>
</div>